cart/urls.py
from django.urls import path
from. import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('',views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove')

]

ecommerce_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,
                                       document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)
    

search_app/urls.py
from django.urls import path
from search_app import views
from . import views
app_name = 'search_app'


urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

shop/urls.py
from django.urls import path

from shop import views
app_name = 'shop'
urlpatterns = [

    path('', views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatDetail'),

]

cart/models.py
from django.db import models

from shop.models import Product
app_name = 'cart'


# Create your models here.
class Cart(models.Model):
    cart_id  = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table = 'cart'
        ordering = ['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return self.product

search_app/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name =models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='Category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug,])

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Product',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated =models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:prodCatDetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse

from cart.models import Cart, CartItem
from shop.models import Product


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id = product_id)
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = _cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product = product, cart = cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product = product, quantity = 1, cart = cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    if request.method == 'POST' and 'pay_button' in request.POST:
        try:
            # Assuming you have a payment processing logic here.
            # Replace this with your actual payment processing code.
            # After successful payment, empty the cart.

            # Process the payment (replace this with your payment processing logic)

            # Empty the cart
            cart_items.delete()

            messages.success(request, 'Payment successful. Your cart is now empty.')
            return HttpResponseRedirect(reverse('shop:allProdCat'))

        except ObjectDoesNotExist:
            messages.error(request, 'Cart not found.')

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

search_app/views.py
from django.shortcuts import render
from django.db.models import Q
from shop.models import Product


# Create your views here.
def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

shop/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from shop.models import Category, Product
from django.core.paginator import Paginator,InvalidPage,EmptyPage


# Create your views here.

def allProdCat(request,c_slug=None):
    c_page = None
    products = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category = c_page, available = True)
    else:
        products_list = Product.objects.all().filter(available=True)
        paginator = Paginator(products_list,6)
        try:
            page = int(request.GET.get('page','1'))
        except:
            page = 1
        try:
            products = paginator.page(page)
        except (EmptyPage,InvalidPage):
            products = paginator.page(paginator.num_pages)
    return render(request, 'category.html' , {'category':c_page, 'products':products})



def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Product.DoesNotExist:
        raise Http404("Product not found")

    return render(request, 'product.html', {'product': product})

templates/base.html
            {% load static %}
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
                <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@10..48,500&display=swap" rel="stylesheet">
                <link rel="stylesheet" href="{% static 'css/custom.css' %}">
                <script src="https://kit.fontawesome.com/18e9964869.js" crossorigin="anonymous"></script>
                <meta name="description" content="{% block metadescription %}{% endblock %}">
                <title>{% block title %}{% endblock %}</title>
            </head>
            <body>
            <div class="container">
                {% include 'header.html' %}
                {% include 'navbar.html' %}
                {% block body %}
                {% endblock %}
            </div>
            {% include 'footer.html' %}
                <script src="{% static 'js/popper.min.js' %}" ></script>
                <script src="{% static 'js/bootstrap.min.js' %}" ></script>
            </body>
            </html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
THIS IS THE CART PAGE. REVIEW YOUR ITEMS AND PLACE AN ORDER.
{% endblock %}

{% block title %}
CART - CHEROKE INC PVT LTD
{% endblock %}

{% block body %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br><h1 class="text-center my_title">YOUR CART</h1>
        <br>
        <p class="text-center">PLEASE CLICK <a href="{% url 'shop:allProdCat' %}">HERE</a> TO CONTINUE SHOPPING</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">YOUR CART</h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">YOUR ITEMS</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{ cart_item.product.get_absolute_url }}"><img src="{{ cart_item.product.image.url }}" alt="" style="width:150px;height:150px" class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{ cart_item.product.name }}
                        <br>
                        SKU : {{ cart_item.product.id }}
                        <br>
                        PRICE : $ {{ cart_item.product.price }}
                        <br>
                        QTY : {{ cart_item.quantity }} X $ {{ cart_item.sub_total }}
                    </td>
                    <td>
                        $ {{ cart_item.sub_total }}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a" ><i class="fa-solid fa-plus" style="color: #000000; custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus" style="color: #000000; custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash" style="color: #000000;"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus" style="color: #000000; custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash" style="color: #000000;"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>
                        CHECKOUT
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Please review your items before proceeding with the payment.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        YOUR TOTAL AMOUNT IS: $ <strong>{{ total }}</strong>
                    </td>
                </tr>
                <tr>
                    <td>
                        <form method="post" action="{% url 'cart:cart_detail' %}">
                            {% csrf_token %}
                            <button type="submit" name="pay_button" class="btn btn-primary">CheckOut</button>
                        </form>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">CONTINUE SHOPPING</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description |truncatewords:155}}
    {% else %}
        WELCOME TO CHEROKE.INC WHERE YOU CAN BUY A VARIETY OF ITEMS
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}} -- CHEROKE INC
    {% else %}
        SEE OUR LATEST ARRIVALS
    {% endif %}
{% endblock %}

{% block body %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
        padding: 0;
    }

    .container {
        flex: 1;
    }

    .my_footer {
        background-color: #000;
        padding: 10px 0;
        color: #343a40;
        margin-left: -120px;
        margin-right: 0;
    }
</style>

<!--TO ADD BACKGROUND IMAGE-->
<!--<style>-->
<!--    body{-->
<!--    background-image:url("{% static 'img/background.jpeg' %}");-->
<!--    background-size: cover;-->
<!--    background-position: center center;-->
<!--</style>-->

{% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'shop:allProdCat' %}">OUR PRODUCTS</a></p>
            </div>
        </div>
    </div>
{% endif %}
<div class="mx-auto container">
    {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
             <div class="container">
                 <div class="col-md-12">
                    <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="OUR PRODUCTS" width="100%;">
                </div>
            </div>
<br>
    <div>
        <h1 class="text-center my_title">OUR PRODUCT COLLECTIONS</h1>
        <p class="text-justify">Hi its our pleasure. Nice to meet you. Enjoy your shopping.</p>
    </div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for i in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4">
                <div class="card text-center d-flex" style="min-width: 15rem; height: 100%;">
                    <a href="{{ i.get_url }}" style="display: flex; justify-content: center; align-items: center; height: 100%;">
                        <img class="card-img-top my_image" src="{{ i.image.url }}" alt="{{ i.name }}" style="max-width: 100%; max-height: 100%; object-fit: contain;">
                    </a>
                    <div class="card-body d-flex flex-column justify-content-between" style="height: 150px;">
                        <h4>{{ i.name }}</h4>
                        <p>{{ i.price }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
            <div class="text-center">
                {% for z in products.paginator.page_range %}
                    <a href="?page={{z}}" class="btn btn-light btn-sm    {% if products.number == z %} active {% endif %}">{{z}}</a>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <br>
</div>
<div class="my_footer">
    <p class="text-center">
        &copy; CHEROKE INC pvt ltd. All rights reserved
    </p>
</div>

{% endblock %}

templates/footer.html
<style>
    .my_footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: #000;
        padding: 10px 0;
        color: #343a40;
    }
</style>

<div class="footer my_footer">
    <p class="text-center">
        &copy; CHEROKE INC pvt ltd. All rights reserved
    </p>
</div>

templates/header.html
{% load static %}
<header style="text-align:center;">
        <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="Logo image" width="240px" height="200px">
                </a>
</header>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allProdCat' %}"><b>Home</b></a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
              {% for x in links %}
              <li><a class="dropdown-item" href="{{ x.get_url }}">{{x.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping fa-bounce" style="color: #000000;"></i>YOUR CART({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
    </div>

    <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass fa-beat" style="color: #000000;"></i>Search</button>
    </form>

  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
    {% if category %}
        {{product.name}} - CHEROKE.INC
    {% endif %}
{% endblock %}

{% block body %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p>
            <a href="{% url 'shop:allProdCat' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}
        </p>
    </div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="width:500px;height:500px;">
        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">PRODUCT DESCRIPTION</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    WE HAVE A VARIETY OF PRODUCTS
{% endblock %}

{% block title %}
    SEARCH
{% endblock %}
{% block body %}
<div class="text-center my_search_text">
    <p>YOU HAVE SEARCHED FOR : <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for i in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4">
            <div class="card text-center d-flex" style="min-width: 15rem;">
                <a href="{{ i.get_url }}" style="display: flex; justify-content: center; align-items: center; height: 100%;">
                    <img class="card-img-top my_image" src="{{ i.image.url }}" alt="{{ i.name }}" style="max-width: 100%; max-height: 100%; object-fit: contain;">
                </a>
                <div class="card-body d-flex flex-column justify-content-between" style="height: 150px;">
                    <h4>{{ i.name }}</h4>
                    <p>{{ i.price }}</p>
                </div>
            </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 RESULTS FOUND</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}